# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

nota = -1

while nota < 0 or nota > 10:
    nota = float(input("Digite uma nota entre zero e dez: "))

    if nota < 0 or nota > 10:
        print("Valor inválido. Digite uma nota entre zero e dez.")

print("Nota válida:", nota)

# Função para calcular a média aritmética
def calcular_media(notas):
    return sum(notas) / len(notas)

# Input do usuário para a quantidade de notas
n = int(input("Digite a quantidade de notas: "))

# Lista vazia para armazenar as notas
notas = []

# Loop para pedir que o usuário insira as notas
for i in range(n):
    nota = float(input(f"Digite a {i + 1}ª nota: "))
    notas.append(nota)

# Chamando a função para calcular a média e imprimindo o resultado
media = calcular_media(notas)
print(f"A média aritmética das notas é: {media}")

while True:
    usuario = input("Digite o nome de usuário: ")
    senha = input("Digite a senha: ")

    if usuario == senha:
        print("Erro: A senha não pode ser igual ao nome de usuário. Tente novamente.")
    else:
        print("Usuário e senha cadastrados com sucesso!")
        break

salario_inicial = float(input("Digite o salário inicial do funcionário: "))

# Definindo o salário inicial e o aumento de 1996
salario_atual = salario_inicial
aumento = 1.5/100

# Calculando o salário atual a partir de 1997
for ano in range(1997, 2023): # Considerando até 2022
    aumento *= 2
    salario_atual *= (1 + aumento)

print(f"O salário atual do funcionário em 2022 é R$ {salario_atual:.2f}")

while True:
    nome = input("Informe o nome (maior que 3 caracteres): ")
    if len(nome) > 3:
        break
    else:
        print("Nome inválido. Digite um nome com mais de 3 caracteres.")

while True:
    idade = int(input("Informe a idade (entre 0 e 150): "))
    if idade >= 0 and idade <= 150:
        break
    else:
        print("Idade inválida. Digite uma idade entre 0 e 150.")

while True:
    salario = float(input("Informe o salário (maior que zero): "))
    if salario > 0:
        break
    else:
        print("Salário inválido. Digite um valor maior que zero.")

while True:
    sexo = input("Informe o sexo ('m' para masculino ou 'f' para feminino): ")
    if sexo in ['m', 'f']:
        break
    else:
        print("Sexo inválido. Digite 'm' para masculino ou 'f' para feminino.")

while True:
    estado_civil = input("Informe o estado civil ('s' para solteiro, 'c' para casado, 'v' para viúvo, 'd' para divorciado): ")
    if estado_civil in ['s', 'c', 'v', 'd']:
        break
    else:
        print("Estado civil inválido. Digite 's' para solteiro, 'c' para casado, 'v' para viúvo, 'd' para divorciado.")

print("\nInformações válidas:")
print("Nome:", nome)
print("Idade:", idade)
print("Salário:", salario)
print("Sexo:", sexo)
print("Estado Civil:", estado_civil)

populacao_A = 80000
taxa_crescimento_A = 0.03
populacao_B = 200000
taxa_crescimento_B = 0.015
anos = 0

while populacao_A < populacao_B:
    populacao_A += populacao_A * taxa_crescimento_A
    populacao_B += populacao_B * taxa_crescimento_B
    anos += 1

print(f"Serão necessários {anos} anos para que a população do país A ultrapasse ou iguale a população do país B.")

def calcular_fatorial(numero):
    fatorial = 1
    for i in range(1, numero + 1):
        fatorial *= i
    return fatorial

numero = int(input("Digite um número inteiro para calcular o fatorial: "))
if numero < 0:
    print("Não é possível calcular o fatorial de um número negativo.")
else:
    resultado = calcular_fatorial(numero)
    print(f"O fatorial de {numero} é: {resultado}")

soma = 0
contador = 0

while True:
    numero = float(input("Digite um número (digite 0 para sair): "))

    if numero == 0:
        break

    soma += numero
    contador += 1

if contador > 0:
    media = soma / contador
    print(f"A média dos números digitados é: {media}")
else:
    print("Nenhum número foi digitado.")

from google.colab import drive
drive.mount('/content/drive')

